# Generated by Django 4.1.1 on 2022-11-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TENANT', 'Tenant'), ('OWNER', 'Owner')], default='OWNER', max_length=6),
        ),
    ]
