# Generated by Django 4.1.1 on 2023-03-25 10:30

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('EARLY_OCCUPIED', 'Early Occupied'), ('ACTIVE', 'Active'), ('PAYMENT_PENDING', 'Payment Pending')], default='PENDING', max_length=20),
        ),
    ]
