# Generated by Django 4.1.1 on 2022-11-04 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='property',
            name='slug',
        ),
        migrations.AlterField(
            model_name='property',
            name='dining_hall',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='kitchen',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='master_bedroon',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='no_of_bathrooms_inside',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='no_of_bathrooms_outside',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='no_of_bedrooms',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='no_of_floors',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='no_of_livingrooms',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='zip_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Invalid Zip Code', regex='^[0-9]{6}$')]),
        ),
    ]
