# Generated by Django 4.1.1 on 2023-03-25 10:44

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_location_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, default='-22.2876834,-49.1607606', max_length=63, null=True),
        ),
    ]
