# Generated by Django 4.1.1 on 2022-11-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('CONFIRMED', 'Confirmed')], default='PENDING', max_length=12),
        ),
    ]
