# Generated by Django 4.1.1 on 2022-11-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image1',
            field=models.ImageField(default='img/fallback.png', upload_to='properties/'),
        ),
    ]
