# Generated by Django 4.1.1 on 2022-11-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
