# Generated by Django 4.1.1 on 2022-11-24 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_delete_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='plot_area',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(500)]),
        ),
    ]
