# Generated by Django 4.1.1 on 2023-03-02 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_alter_comment_options_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.AlterField(
            model_name='property',
            name='feature_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='feature_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='no_of_bathrooms_outside',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
